# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARTIFACT_RETENTION_DAYS_DEFAULT: 1
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set env vars
        run: |
          if [ -n "${SSTATE_DIR}" ]; then
            export SSTATE_DIR=${SSTATE_DIR}/swupdate-oe4t-master
            echo "SSTATE_DIR=${SSTATE_DIR}" >> "$GITHUB_ENV"
          fi
          echo "Running kas build with SSTATE_DIR=${SSTATE_DIR} DL_DIR=${DL_DIR}"
          if [ -n "${ARTIFACT_RETENTION_DAYS}" ]; then
            export ARTIFACT_RETENTION_DAYS=${ARTIFACT_RETENTION_DAYS_DEFAULT}
            echo "ARTIFACT_RETENTION_DAYS=${ARTIFACT_RETENTION_DAYS}" >> "$GITHUB_ENV"
          fi
          echo "Using ARTIFACT_RETENTION_DAYS=${ARTIFACT_RETENTION_DAYS}"
 
      - name: Build kas swupdate demo
        run: |
          export buildproj=swupdate-oe4t
          echo "buildproj=${buildproj}" >> "$GITHUB_ENV"
          echo "Making build directory ${buildproj}"
          mkdir ${buildproj}
          echo "Changing to build directory ${buildproj}"
          cd ${buildproj}
          echo "running kas container build for ${buildproj}"
          kas-container build ../kas/${buildproj}.yml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.buildproj }}
          path: |
           ${{ env.buildproj}}/build/tmp/deploy/images/*/*.tegraflash.tar.zst
           ${{ env.buildproj}}/build/tmp/deploy/images/*/*.swu
           retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
        
      - name: Build kas swupdate rootfs overlay demo
        run: |
          if [ -n "${SSTATE_DIR}" ]; then
            export SSTATE_DIR=${SSTATE_DIR}/swupdate-oe4t-master
          fi
          echo "Running kas build with SSTATE_DIR=${SSTATE_DIR} DL_DIR=${DL_DIR}"
          export buildproj=swupdate-rootfs-overlay-oe4t
          echo "buildproj=${buildproj}" >> "$GITHUB_ENV"
          mkdir ${buildproj}
          cd ${buildproj}
          kas-container build ../kas/${buildproj}.yml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.buildproj }}
          path: |
           ${{ env.buildproj }}/build/tmp/deploy/images/*/*.tegraflash.tar.zst
           ${{ env.buildproj }}/build/tmp/deploy/images/*/*.swu
           retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
