# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARTIFACT_RETENTION_DAYS_DEFAULT: 3
  MACHINE: jetson-orin-nano-devkit-nvme
  SWUPDATE_CORE_IMAGE_NAME: demo-image-base

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        buildproj: [ swupdate-oe4t, swupdate-rootfs-overlay-oe4t ]
        branch: [ kirkstone, scarthgap-l4t-r35.x, scarthgap, master ]
    steps:
      - uses: actions/checkout@v4

      - name: Set env vars
        run: |
          if [ -n "${SSTATE_DIR}" ]; then
            export SSTATE_DIR=${SSTATE_DIR}/swupdate-oe4t-${{ matrix.branch }}
            echo "SSTATE_DIR=${SSTATE_DIR}" >> "$GITHUB_ENV"
          fi
          echo "Running kas build with SSTATE_DIR=${SSTATE_DIR} DL_DIR=${DL_DIR}"
          if [ -n "${ARTIFACT_RETENTION_DAYS}" ]; then
            export ARTIFACT_RETENTION_DAYS=${ARTIFACT_RETENTION_DAYS_DEFAULT}
            echo "ARTIFACT_RETENTION_DAYS=${ARTIFACT_RETENTION_DAYS}" >> "$GITHUB_ENV"
          fi
          echo "Using ARTIFACT_RETENTION_DAYS=${ARTIFACT_RETENTION_DAYS}"
 
      - name: Build ${{ matrix.buildproj }} branch ${{ matrix.branch }}
        run: |
          export builddir=${{ matrix.buildproj }}-${{ matrix.branch }}
          echo "builddir=${builddir}" >> "$GITHUB_ENV"
          echo "Making build directory ${builddir}"
          mkdir ${builddir}
          echo "Changing to build directory ${builddir}"
          cd ${builddir}
          echo "running kas container build for ${{ matrix.buildproj }} on branch ${{ matrix.branch }}"
          kas-container build ../kas/${{ matrix.buildproj}}.yml:../kas/include/${{ matrix.branch }}.yml

      - name: Upload artifacts for ${{ matrix.buildproj }} branch ${{ matrix.branch }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.buildproj }}-${{ matrix.branch }}-${{ env.SWUPDATE_CORE_IMAGE_NAME }}-${{ env.MACHINE }}
          path: |
           ${{ env.builddir }}/build/tmp/deploy/images/${{ env.MACHINE }}/${{ env.SWUPDATE_CORE_IMAGE_NAME}}-${{ env.MACHINE }}.tegraflash.tar.*
           ${{ env.builddir }}/build/tmp/deploy/images/${{ env.MACHINE }}/${{ env.SWUPDATE_CORE_IMAGE_NAME}}-${{ env.MACHINE }}.rootfs.tegraflash.tar.*
           ${{ env.builddir }}/build/tmp/deploy/images/${{ env.MACHINE }}/${{ env.SWUPDATE_CORE_IMAGE_NAME}}-${{ env.MACHINE }}.swu
           retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

